import React from 'react';
import Head from 'next/head';
import styles from '@/styles/Home.module.scss';

import {
  AboutCourse,
  Contact,
  CourseDetails,
  Footer,
  Header,
  Learn,
  Partners,
  Reviews,
  Stats,
  WhyUs,
} from '@/components';

export default function Home() {
  const headerRef = React.useRef(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <Stats />
        <AboutCourse />
        <CourseDetails />
        <Learn />
        <WhyUs />
        <Partners />
        <Reviews />
        <Contact />
      </main>

      <Footer />
    </>
  );
}
